version: '3.2'

services:

  tomcat:
    image: tomcat:8.5.38-jre11
    container_name: tomcat_web_app
    ports:
      - "127.0.0.1:18080:8080"
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
